// Shared column building blocks reused by every aggregate (Gopher DB conventions):
// UUID v4 PKs, UTC timestamptz timestamps, soft-delete columns, and optional actor
// columns. Column keys are camelCase; `casing: 'snake_case'` maps them to snake_case.

import { boolean, timestamp, uuid } from 'drizzle-orm/pg-core';

/** UUID v4 primary key, generated by Postgres. */
export const idColumn = {
  id: uuid().primaryKey().defaultRandom(),
};

/** Lifecycle timestamps, stored as UTC `timestamptz`. */
export const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
};

/** Soft-delete contract: hidden, not erased. */
export const softDeleteColumns = {
  isActive: boolean().notNull().default(true),
  deletedAt: timestamp({ withTimezone: true }),
};

/** Optional actor attribution columns. */
export const actorColumns = {
  createdBy: uuid(),
  updatedBy: uuid(),
};

/** Standard base columns: id + timestamps + soft-delete. */
export const baseColumns = {
  ...idColumn,
  ...timestamps,
  ...softDeleteColumns,
};

/** Base columns plus created_by/updated_by attribution. */
export const baseColumnsWithActor = {
  ...baseColumns,
  ...actorColumns,
};
